# Generated by Django 4.2.2 on 2023-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="squad",
            name="name",
            field=models.CharField(default="No name", max_length=200),
            preserve_default=False,
        ),
    ]
