# Generated by Django 4.2.2 on 2023-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_course_id_alter_payment_url_revenue_refund_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
