# Generated by Django 4.2.2 on 2023-06-29 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_lesson_is_free"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="paid",
            new_name="is_premium",
        ),
    ]
